### ISSUE TITLE
json read error when recieveing push

### ISSUE THREAD

**Issue by dotterian** [Boteium/bashbullet#11]
Application succesfully installed with all dependencies but when i start ./bashbullet i get
```
json read error: line 2 column 0: unable to decode byte 0xba
json read error: line 2 column 0: unable to decode byte 0xba
```
And each time i get push i get the same output and no notification as a result.

Turned out that `<<<` is adding new line at the end of stream and jshon can't handle it and fails.

I had to rewrite all jshon calls via pipe like that:
```sh
DEVS=(`echo "$DEVS_RAW"|jshop -e devices|…`)
```

And after this fix it's working good for me.

**Comment by Boteium** [comment]
Thanks. I will fix it.
