### ISSUE TITLE
xdg-open variable is actually xdg_open

### ISSUE THREAD

**Issue by hashworks** [Boteium/bashbullet#4]
See https://github.com/Boteium/bashbullet/blob/master/config_example#L57

xdg-open won't work because bash would interpret it:
```bash
xdg-open=test
-bash: xdg-open=test: Command not found.
```

**Comment by Boteium** [comment]
Thank you !
should be fixed by now.

**Comment by hashworks** [comment]
Note that you can [close issue reports by refering to them in your commits](https://github.com/blog/1386-closing-issues-via-commit-messages).
