### ISSUE TITLE
API_KEY

### ISSUE THREAD

**Issue by TheRojam** [Boteium/bashbullet#6]
In *README.md* you wrote
> Place your api key token in ~/.bashbullet/config
> API_KEY="my_pushbullet_api_key" 

I looked the api-docs but did not any information where to get an api-key for bashpullet

**Comment by Boteium** [comment]
You need to create an access token from pushbullet website. Pushbullet website is now offering access token by default instead of api key, which may be a little confusing. Simply log into your pushbullet account and create an access token.

**Comment by TheRojam** [comment]
I got it thanks alot :)
